services:
  neo4j:
    image: neo4j:5.26
    restart: unless-stopped
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}

      # ↓↓↓ ВОТ ЭТИ 4 — РОВНО ТАК, с двойными __ перед address ↓↓↓
      NEO4J_server_default__listen__address: "0.0.0.0"     # -> server.default_listen_address
      NEO4J_server_default__advertised__address: "neo4j"   # -> server.default_advertised_address
      NEO4J_server_bolt__listen__address: ":7687"          # -> server.bolt.listen_address
      NEO4J_server_bolt__advertised__address: "neo4j:7687" # -> server.bolt.advertised_address

    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7474/ready || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 60s
    ports:
      - "7474:7474"
      - "7687:7687"

  graphiti-app:
    build: .
    restart: unless-stopped
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}

      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GEMINI_LLM_MODEL: ${GEMINI_LLM_MODEL}
      GEMINI_EMB_MODEL: ${GEMINI_EMB_MODEL}
      GEMINI_RERANK_MODEL: ${GEMINI_RERANK_MODEL}

      GRAPHITI_TELEMETRY_ENABLED: ${GRAPHITI_TELEMETRY_ENABLED}
      SEMAPHORE_LIMIT: ${SEMAPHORE_LIMIT}
      USE_PARALLEL_RUNTIME: ${USE_PARALLEL_RUNTIME}
      TZ: ${TZ}
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - "8000:8000"
volumes:
  neo4j_data: {}
