services:
  neo4j:
    image: neo4j:5.26
    restart: unless-stopped
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
      # => server.default_listen_address=0.0.0.0
      NEO4J_server_default_listen__address: "0.0.0.0"    
      # => server.default_advertised_address=neo4j
      NEO4J_server_default_advertised__address: "neo4j"    
      # => server.bolt.listen_address=:7687
      NEO4J_server_bolt_listen__address: ":7687"    
      # => server.bolt.advertised_address=neo4j:7687
      NEO4J_server_bolt_advertised__address: "neo4j:7687"


      # Опционально: отключить строгую валидацию на время отладки
      # NEO4J_server_config_strict__validation__enabled: "false"
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7474/ready || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 60s
    ports:
      - "7474:7474"
      - "7687:7687"

  graphiti-app:
    build: .
    restart: unless-stopped
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}

      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      # Опционально:
      # GRAPHITI_TELEMETRY_ENABLED: "false"   # отключить телеметрию :contentReference[oaicite:6]{index=6}
      # SEMAPHORE_LIMIT: "10"                 # конкурентность ingestion (по умолчанию 10) :contentReference[oaicite:7]{index=7}
      # USE_PARALLEL_RUNTIME: "false"         # параллельный рантайм Neo4j (Aura/Community не поддерживают) :contentReference[oaicite:8]{index=8}

      TZ: Europe/Amsterdam
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  neo4j_data: {}
